#!/bin/bash
PKG_LIST=$(find -maxdepth 1 -type d -not -name ".git" -a -not -name ".")
for PKG in $PKG_LIST; do
  if [ -f "${PKG}/PKGBUILD" ]; then
    (cd ${PKG};
    pkgvdiff;
    cd ..;)
  else
    (cd ${PKG};
    dirvdiff;
    cd ..)
  fi
done
