#!/bin/bash

source /etc/makepkg.conf

EXTRA_VOLUMES=""
[ ! -z "${PKGDEST}" ] && EXTRA_VOLUMES="-v ${PKGDEST}:${PKGDEST}"
[ ! -z "${SRCDEST}" ] && EXTRA_VOLUMES="${EXTRA_VOLUMES} -v ${SRCDEST}:${SRCDEST}"
[ -d ${HOME}/.gnupg/ ] && EXTRA_VOLUMES="${EXTRA_VOLUMES} -v  ${HOME}/.gnupg:/home/builder/.gnupg:ro"

set -x
MAKEPKGCONF=/etc/makepkg.conf
[ -f /etc/makepkg.conf.ppc64le ] && MAKEPKGCONF=/etc/makepkg.conf.ppc64le

PACMANCONF=/etc/pacman.conf
[ -f /etc/pacman.conf.ppc64le ] && PACMANCONF=/etc/pacman.conf.ppc64le

docker run \
   --name $(basename `pwd`)_builder \
   --rm \
   -v $(pwd):/build \
   -v ${MAKEPKGCONF}:/etc/makepkg.conf:ro \
   -v ${PACMANCONF}:/etc/pacman.conf:ro  ${EXTRA_VOLUMES} \
   -v /var/cache/pacman:/var/cache/pacman \
   -w /build \
   --user 1000:1000 \
   kth5/archpower-builder:latest \
   domakepkg-real $@
