#!/bin/bash

THEIR_REPO=${HOME}/code/arch/packages
THEIR_COMMUNITY=${HOME}/code/arch/community

_mypkg=$(basename `pwd`)

[ -f ${THEIR_REPO}/${_mypkg}/trunk/PKGBUILD ] \
  && diff ${THEIR_REPO}/${_mypkg}/trunk/PKGBUILD PKGBUILD

[ -f ${THEIR_COMMUNITY}/${_mypkg}/trunk/PKGBUILD ] \
  && diff ${THEIR_COMMUNITY}/${_mypkg}/trunk/PKGBUILD PKGBUILD
