#!/bin/bash
source PKGBUILD
source /etc/makepkg.conf
source /usr/share/makepkg/util/message.sh

_myarch=${CARCH}

if [ -z $(printf '%s\n' "${arch[@]}" | grep "^${_myarch}$") ]; then
  _hasarch="${arch[@]} ${_myarch} powerpc"
else
  _hasarch="${arch[@]}"
fi

_hasmaintainer=$(grep '# POWER Maintainer:' PKGBUILD | wc -l)

[ ! -z "${PACKAGER}" -a ${_hasmaintainer} -lt 1 ] && \
	sed -i "1i# POWER Maintainer: ${PACKAGER}" PKGBUILD

if [ ! ${arch} = 'any' ]; then
	sed -i "s@^arch=.*@arch=(${_hasarch})@g" PKGBUILD
fi

for key in ${validpgpkeys[@]}; do
	gpg --keyserver keyserver.ubuntu.com --recv-keys ${key} 2>/dev/null
done


# warn packages that can't build/work for non-x86
WARN_PKGS=(nasm yasm fwupd luajit)
for pkg in ${depends[@]}; do
	for warn_pkg in ${WARN_PKGS[@]}; do
		[ ${pkg} = ${warn_pkg} ] && warning ":: ${pkg} in depends can't build with/for ${CHOST}!"
	done	
done

for pkg in ${makedepends[@]}; do
	for warn_pkg in ${WARN_PKGS[@]}; do
		[ ${pkg} = ${warn_pkg} ] && warning ":: ${pkg} in makedepends can't build with/for ${CHOST}!"
	done	
done
